Add exception inheritance on import settings module. Add initial error message.
charlsagente/python-settings-module pull request #6
Opened 2024-11-25 18:39 UTC by cthtuf

Hi! 
I like your project and use it in all my non-django projects. Thank you for it!

From time to time I'm facing with issue when settings file contains errors. For example I'm using python-decouple and when I don't specify default value for env and it wasn't passed properly, then I get ImproperlyConfigured exception, but it's not so informative. I suggest to add a bit details which would make it easier to debug and fix.
It would be great to have this changes in a new version.
Here is screenshots with logs to see the difference:

Before: 
![image](https://github.com/user-attachments/assets/ca87c622-6548-4b0a-be99-dfb7c997bd4c)

---
After:
![image](https://github.com/user-attachments/assets/62a6e793-f492-4772-9d8f-53a4b7537fb0)

2024-11-25 20:20 UTC, charlsagente commented
Hi @cthtuf, I'm glad you found this project useful, I use it in all my non-django projects too!
Thanks for creating a PR, I will review it, test it and we can continue from there.

2024-11-25 20:34 UTC, charlsagente requested changes

2024-11-25 20:34 UTC, charlsagente commented on python_settings/__init__.py
> +            raise ImproperlyConfigured(f"Cannot import SETTINGS_MODULE: {ie}") from ie
Understood. I'd like to ensure we're considerate of those still using Python 2.7 and versions <= 3.5, as there are still some users relying on them. What approach can we take to ensure backward compatibility?

2024-11-26 07:06 UTC, cthtuf commented on python_settings/__init__.py
> +            raise ImproperlyConfigured(f"Cannot import SETTINGS_MODULE: {ie}") from ie
Sure, updated the PR. I removed exception inheritance and replaced f-string with formatted string. Tested it locally with python2.7

2024-11-27 05:41 UTC, charlsagente approved these changes
Looking good, I tested on different Python versions. 
I can add test coverage in the future for the generic Exception case.

2024-11-27 05:45 UTC, merged